### ISSUE TITLE
Always download parent pom.xml from http://repo.maven.apache.org/maven2

### ISSUE THREAD

**Issue by cfmcgrady** [sbt/sbt-pom-reader#79]
should respect user-configured proxy repositories settings.

```shell
# ./build/sbt
Using /usr/local/jdk as default JAVA_HOME.
Note, this will be overridden by -java-home if it is set.
[info] welcome to sbt 1.9.0 (Oracle Corporation Java 1.8.0_191)
[info] loading settings for project spark-build from plugins.sbt ...
[info] loading project definition from /root/spark/project
[info] Fetching artifacts of
[info] Fetched artifacts of
org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model for or
g.apache.spark:spark-parent_2.12:3.5.0-SNAPSHOT
[FATAL] Non-resolvable parent POM for org.apache.spark:spark-parent_2.12:3.5.0-SNAPSHOT: Could not transfer artifact org.apache:apache:pom:18 from/to central (http://repo.maven.apache.org/maven2): repo.maven.apache.org: Temporary failure in nameresolution and 'parent.relativePath' points at wrong local POM @ line 22, column 11

        at org.apache.maven.model.building.DefaultModelProblemCollector.newModelBuildingException(DefaultModelProblemCollector.java:197)
        at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1114)
        at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:860)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:344)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:252)
        at sbtpomreader.MavenPomResolver.loadEffectivePom(MavenPomResolver.scala:63)
        at sbtpomreader.package$.loadEffectivePom(package.scala:40)
        at sbtpomreader.MavenProjectHelper$.makeProjectTree(MavenProjectHelper.scala:145)
        at sbtpomreader.MavenProjectHelper$.makeReactorProject(MavenProjectHelper.scala:51)
        at sbtpomreader.PomBuild.projectDefinitions(PomBuild.scala:23)
        at sbtpomreader.PomBuild.projectDefinitions$(PomBuild.scala:20)
        at SparkBuild$.projectDefinitions(SparkBuild.scala:523)
        at sbt.internal.Load$.projectsFromBuild(Load.scala:819)
        at sbt.internal.Load$.$anonfun$loadUnit$8(Load.scala:719)
        at scala.collection.immutable.Stream.flatMap(Stream.scala:489)
        at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:719)
        at sbt.internal.Load$.timed(Load.scala:1406)
        at sbt.internal.Load$.loadUnit(Load.scala:694)
        at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:492)
        at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:180)
        at sbt.internal.BuildLoader.apply(BuildLoader.scala:245)
        at sbt.internal.Load$.loadURI$1(Load.scala:554)
        at sbt.internal.Load$.loadAll(Load.scala:570)
        at sbt.internal.Load$.loadURI(Load.scala:500)
        at sbt.internal.Load$.load(Load.scala:479)
        at sbt.internal.Load$.$anonfun$apply$1(Load.scala:241)
        at sbt.internal.Load$.timed(Load.scala:1406)
        at sbt.internal.Load$.apply(Load.scala:241)
        at sbt.internal.Load$.defaultLoad(Load.scala:56)
        at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:963)
        at sbt.BuiltinCommands$.doLoadProject(Main.scala:963)
        at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:916)
        at sbt.Command$.$anonfun$applyEffect$4(Command.scala:150)
        at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
        at sbt.Command$.process(Command.scala:189)
        at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:245)
        at scala.Option.getOrElse(Option.scala:189)
        at sbt.MainLoop$.process$1(MainLoop.scala:245)
        at sbt.MainLoop$.processCommand(MainLoop.scala:278)
        at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:163)
        at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
        at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
        at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:163)
        at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
        at sbt.MainLoop$.next(MainLoop.scala:163)
        at sbt.MainLoop$.run(MainLoop.scala:144)
        at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:119)
        at sbt.io.Using.apply(Using.scala:27)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:112)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:66)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:51)
        at sbt.MainLoop$.runLogged(MainLoop.scala:42)
        at sbt.StandardMain$.runManaged(Main.scala:224)
        at sbt.xMain$.$anonfun$run$11(Main.scala:134)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withIn(Console.scala:230)
        at sbt.internal.util.Terminal$.withIn(Terminal.scala:609)
        at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:389)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withOut(Console.scala:167)
        at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:599)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withErr(Console.scala:196)
        at sbt.internal.util.Terminal$.withOut(Terminal.scala:599)
        at sbt.internal.util.Terminal$.withStreams(Terminal.scala:389)
        at sbt.xMain$.withStreams$1(Main.scala:87)
        at sbt.xMain$.run(Main.scala:122)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:57)
        at sbt.xMain.run(Main.scala:46)
        at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
        at xsbt.boot.Launch$.run(Launch.scala:149)
        at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
        at xsbt.boot.Launch$.launch(Launch.scala:159)
        at xsbt.boot.Launch$.apply(Launch.scala:44)
        at xsbt.boot.Launch$.apply(Launch.scala:21)
        at xsbt.boot.Boot$.runImpl(Boot.scala:78)
        at xsbt.boot.Boot$.run(Boot.scala:73)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
[error] org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model for org.apache.spark:spark-parent_2.12:3.5.0-SNAPSHOT
[error] [FATAL] Non-resolvable parent POM for org.apache.spark:spark-parent_2.12:3.5.0-SNAPSHOT: Could not transfer artifact org.apache:apache:pom:18 from/to central (http://repo.maven.apache.org/maven2): repo.maven.apache.org: Temporary failurein name resolution and 'parent.relativePath' points at wrong local POM @ line 22, column 11
[error] Use 'last' for the full log.
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

**Comment by gemelen** [comment]
@cfmcgrady Thank you for raising the issue
